#SERVER
server.local=false
server.test=false
server.daoautoupdater=false
server.activation_fee=30000
server.sv=1
server.name=NRO ARN
server.ip=127.0.0.1
server.port=14445
server.sv1=NRO ARN:127.0.0.1:14445:0,0,0
server.waitlogin=2
server.maxperip=3
server.maxplayer=1000
server.expserver=1
server.max_items_bag=90
server.max_items_box=102

#DATABASE
database.driver=com.mysql.cj.jdbc.Driver
database.host=localhost
database.port=3306
database.name=nro_arn
database.user=root
database.pass=
database.min=5
database.max=20
database.lifetime=180000

#EVENT Định dạng thời gian: yyyy-MM-dd HH:mm:ss. Để trống start/end nếu không giới hạn thời gian.
# Sự kiện tết
event.lunar_new_year.enabled=false
event.lunar_new_year.start=
event.lunar_new_year.end=

# Sự kiện quốc tế phụ nữ
event.international_womens_day.enabled=false
event.international_womens_day.start=
event.international_womens_day.end=

# Sự kiện Noel
event.christmas.enabled=false
event.christmas.start=
event.christmas.end=

# Sự kiện Halloween
event.halloween.enabled=false
event.halloween.start=
event.halloween.end=

# Sự kiện 10/03
event.hung_vuong.enabled=true
event.hung_vuong.start=
event.hung_vuong.end=

# Sự kiện trung thu
event.trung_thu.enabled=false
event.trung_thu.start=
event.trung_thu.end=

# Sự kiện đua top
event.top_up.enabled=true
event.top_up.start=
event.top_up.end=

# Sự kiện hè
event.summer.enabled=true
event.summer.start=2026-07-09 00:00:00
event.summer.end=2026-08-30 23:59:59

#50 = 0.5%
#100 = 1%
#500 = 5%
#1000 = 10%
#5000 = 50%
#RARE ITEM DROP
rareitem.enabled=true
rareitem.drop_rate_default=10000
rareitem.drop_rate_special=10000
rareitem.normal_maps=0,1,2,7,14,21,27,156,157,158,159,160,161,162,163,164,165,166,167,168,169
rareitem.special_maps=92,93,94,96,97,98,99,100,102,103

rareitem.rate_red=4000
rareitem.rate_yellow=5000
rareitem.rate_blue=1000

rareitem.min_percent=5
rareitem.max_percent=20
rareitem.min_absolute=500
rareitem.max_absolute=3000
rareitem.allow_duplicate_percent=60

# Cấu hình Nâng Cấp Pet Rồng Nhí
pet_rong_nhi.exp_req=10000
pet_rong_nhi.upgrade_percent=50
pet_rong_nhi.add_percent=5
pet_rong_nhi.add_absolute=10

# Ty le roi Set Kich Hoat (1/x)
# Cach tinh phan tram: (1 / x) * 100
# Vi du: 500 = 0.2%
server.rate.skh.normal=500
# Vi du: 400 = 0.25%
server.rate.skh.upskh=400
# Vi du: 300 = 0.33%
server.rate.skh.private=300

# Ty le roi Manh Set Kich Hoat (1/x)
# Vi du: 3 = 33.33%
server.rate.manhskh=3

# Cấu hình Thú Cưỡi
thu_cuoi.flying_mobs=7,8,9,28,29,30,37,49,50,109
thu_cuoi.abs_min=1000
thu_cuoi.abs_max=5000
thu_cuoi.pct_min=5
thu_cuoi.pct_max=15
thu_cuoi.exp_req=10000
thu_cuoi.upgrade_percent=50
thu_cuoi.add_percent=3
thu_cuoi.add_absolute=20

