#SERVER
server.local=false
server.test=false
server.daoautoupdater=false
server.sv=1
server.name=NRO ARN
server.ip=127.0.0.1
server.port=14445
server.sv1=NRO ARN:127.0.0.1:14445:0,0,0
server.waitlogin=2
server.maxperip=3
server.maxplayer=1000
server.expserver=1

#DATABASE
database.driver=com.mysql.cj.jdbc.Driver
database.host=localhost
database.port=3306
database.name=nro_arn
database.user=root
database.pass=
database.min=5
database.max=20
database.lifetime=180000

#EVENT Định dạng thời gian: yyyy-MM-dd HH:mm:ss. Để trống start/end nếu không giới hạn thời gian.
# Sự kiện tết
event.lunar_new_year.enabled=false
event.lunar_new_year.start=
event.lunar_new_year.end=

# Sự kiện quốc tế phụ nữ
event.international_womens_day.enabled=false
event.international_womens_day.start=
event.international_womens_day.end=

# Sự kiện Noel
event.christmas.enabled=false
event.christmas.start=
event.christmas.end=

# Sự kiện Halloween
event.halloween.enabled=false
event.halloween.start=
event.halloween.end=

# Sự kiện 10/03
event.hung_vuong.enabled=true
event.hung_vuong.start=
event.hung_vuong.end=

# Sự kiện trung thu
event.trung_thu.enabled=false
event.trung_thu.start=
event.trung_thu.end=

# Sự kiện đua top
event.top_up.enabled=true
event.top_up.start=
event.top_up.end=

# Sự kiện hè
event.summer.enabled=true
event.summer.start=2026-07-09 00:00:00
event.summer.end=2026-08-30 23:59:59
